name: "Deploy para homologacao"

on:
  push:
    branches: [ "homolog" ]
  pull_request:
    branches: [ "homolog" ]

jobs:
  build_deploy:

    runs-on: ubuntu-latest

    steps:
      - name: "Clone do codigo" 
        uses: actions/checkout@v4

      - name: "Copiando arquivos para homologacao"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "144.217.58.187"
          username: "demostenes"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "~/number"

      - name: "Build aplicacao"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "144.217.58.187"
          username: "demostenes"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/number
            docker compose exec faturamento composer install --no-progress -a
            docker compose exec faturamento php artisan migrate
            docker compose exec faturamento php artisan route:cache
            docker compose exec faturamento php artisan optimize
            mkdir  faturamento/storage/framework/cache/laravel-excel
            chmod 777 faturamento/storage/framework/cache/laravel-excel